// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function GetArticles() {
  return window['go']['main']['App']['GetArticles']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetWordBook() {
  return window['go']['main']['App']['GetWordBook']();
}

export function MarkReviewed(arg1) {
  return window['go']['main']['App']['MarkReviewed'](arg1);
}

export function RemoveWord(arg1) {
  return window['go']['main']['App']['RemoveWord'](arg1);
}

export function SaveArticle(arg1, arg2) {
  return window['go']['main']['App']['SaveArticle'](arg1, arg2);
}

export function SaveWord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWord'](arg1, arg2, arg3);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}