// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteArticle(arg1:number):Promise<void>;

export function GetArticles():Promise<Array<main.Article>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetWordBook():Promise<Array<main.WordBookItem>>;

export function MarkReviewed(arg1:string):Promise<void>;

export function RemoveWord(arg1:string):Promise<void>;

export function SaveArticle(arg1:string,arg2:string):Promise<void>;

export function SaveWord(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function Translate(arg1:string):Promise<main.TranslateResult>;

export function UpdateNote(arg1:string,arg2:string):Promise<void>;